// Leyenda de los íconos de trazo uniforme (fuente /public/fonts/iconos.woff2, Lucide, licencia ISC).
// En el código aparecen como un carácter invisible del rango privado (se ve como un cuadradito en el editor).
// Este archivo solo documenta cuál es cuál; no se importa desde ningún lado.
export const ICONOS_LEYENDA = {
  '\ue04c': 'arrow-left',
  '\ue06d': 'check',
  '\ue087': 'clipboard-list',
  '\ue088': 'clock',
  '\ue097': 'coffee',
  '\ue09c': 'compass',
  '\ue0b3': 'download',
  '\ue0bb': 'eye',
  '\ue0bc': 'eye-off',
  '\ue0d7': 'flask-conical',
  '\ue103': 'library',
  '\ue110': 'mail',
  '\ue11f': 'moon',
  '\ue13f': 'plus',
  '\ue153': 'search',
  '\ue17a': 'sun',
  '\ue18c': 'trash-2',
  '\ue191': 'triangle-alert',
  '\ue19d': 'user',
  '\ue1b0': 'x',
  '\ue1c1': 'lightbulb',
  '\ue1e9': 'sprout',
  '\ue233': 'graduation-cap',
  '\ue29b': 'puzzle',
  '\ue2a1': 'bar-chart-3',
  '\ue2dd': 'leaf',
  '\ue416': 'sparkles',
  '\ue4a7': 'key-round',
  '\ue4b2': 'presentation',
};
